- Target: nmaguiar/baseutils:latest (alpine 3.23.0_alpha20250612)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-32462
    PkgID: sudo@1.9.17-r0
    PkgName: sudo
    PkgIdentifier:
      PURL: pkg:apk/alpine/sudo@1.9.17-r0?arch=x86_64&distro=3.23.0_alpha20250612
      UID: f452168152faeaa2
    InstalledVersion: 1.9.17-r0
    FixedVersion: 1.9.17_p1-r0
    Status: fixed
    Layer:
      Digest: sha256:6d4311eb70f1e3fcf9763fe1649151b6c37f446618c562a377f16b912b6f3abb
      DiffID: sha256:cf8f4a60b385996e7680949265f582b6aa5dda4d7432241e87c8670a5e404557
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32462
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: '[Local Privilege Escalation via host option]'
    Description: Sudo's host (`-h` or `--host`) option is intended to be used in conjunction with the list option (`-l` or `--list`) to list a user's sudo privileges on a host other than the current one.  However, due to a bug it was not restricted to listing privileges and could be used when running a command via `sudo` or editing a file with `sudoedit`.  Depending on the rules present in the sudoers file this could allow a local privilege escalation attack. Sudo versions 1.8.8 to 1.9.17 inclusive are affected.
    Severity: HIGH
    VendorSeverity:
      ubuntu: 3
    References:
    - https://www.cve.org/CVERecord?id=CVE-2025-32462
    - https://www.sudo.ws/security/advisories/host_any/
  - VulnerabilityID: CVE-2025-32463
    PkgID: sudo@1.9.17-r0
    PkgName: sudo
    PkgIdentifier:
      PURL: pkg:apk/alpine/sudo@1.9.17-r0?arch=x86_64&distro=3.23.0_alpha20250612
      UID: f452168152faeaa2
    InstalledVersion: 1.9.17-r0
    FixedVersion: 1.9.17_p1-r0
    Status: fixed
    Layer:
      Digest: sha256:6d4311eb70f1e3fcf9763fe1649151b6c37f446618c562a377f16b912b6f3abb
      DiffID: sha256:cf8f4a60b385996e7680949265f582b6aa5dda4d7432241e87c8670a5e404557
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32463
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: '[Local Privilege Escalation via chroot option]'
    Description: An attacker can leverage sudo's `-R` (`--chroot`) option to run arbitrary commands as root, even if they are not listed in the sudoers file. Sudo versions 1.9.14 to 1.9.17 inclusive are affected.
    Severity: HIGH
    VendorSeverity:
      ubuntu: 3
    References:
    - https://www.cve.org/CVERecord?id=CVE-2025-32463
    - https://www.sudo.ws/security/advisories/chroot_bug/
- Target: Java
  Class: lang-pkgs
  Type: jar
