stdout: {}
stderr: "[vuln] Vulnerability scanning is enabled\n2026-02-08T07:24:53Z\tINFO\t[secret] Secret scanning is enabled\n2026-02-08T07:24:53Z\tINFO\t[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning\n2026-02-08T07:24:53Z\tINFO\t[secret]"
exitcode: 1
cmd: docker run --pull always --rm -v trivy-db:/root/.cache/trivy aquasec/trivy -f json  image nmaguiar/baseutils:deb
