name: Scan Images

on:
  workflow_dispatch:
  schedule:
  - cron: '07 7 * * *'

jobs:
  Scan-Images:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Scan images
    steps      :
    - uses: actions/checkout@v4
      name: Checkoout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-nightly
        path: /tmp/oaf

    - name: Restore the trivy databases from cache
      run : |
        wget https://openaf.io/trivy-db.tgz
        docker run --rm -v trivy-db:/volume -v $(pwd):/backup busybox tar xzf /backup/trivy-db.tgz -C /volume

    - uses: openaf/ojob-action@v7
      name: Check latest
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/baseutils:latest file=.github/sec-latest.svg reportFile=.github/sec-latest.yaml'
        dist: 'nightly'

    - uses: openaf/ojob-action@v7
      name: Generate sec-latest.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-latest.yaml file=.github/sec-latest.md'
        dist: 'nightly'

    - uses: openaf/ojob-action@v7
      name: Check deb
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/baseutils:deb file=.github/sec-deb.svg reportFile=.github/sec-deb.yaml'
        dist: 'nightly'

    - uses: openaf/ojob-action@v7
      name: Generate sec-deb.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-deb.yaml file=.github/sec-deb.md'
        dist: 'nightly'

    - uses: openaf/ojob-action@v7
      name: Generate sec-deb.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-deb.yaml file=.github/sec-deb.md'
        dist: 'nightly'

    - uses: openaf/ojob-action@v7
      name: Update badges
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ badge\ {{date}}/{{time}}" title="Update\ badge" paths=.github/'
        dist: 'nightly'